site_name: ETOS
site_url: https://etos.readthedocs.io
site_description: ETOS is a test orchestration framework for testing complex systems

repo_url: https://github.com/eiffel-community/etos

nav:
  - Home: ./index.md
  - Getting started: ./getting_started/index.md
  - Installation: ./getting_started/installation.md
  - Authors: ./AUTHORS.md
  - License: ./LICENSE.txt
  - Contributing: https://github.com/eiffel-community/.github/blob/master/CONTRIBUTING.md
  - Code of conduct: https://github.com/eiffel-community/.github/blob/master/CODE_OF_CONDUCT.md
theme: readthedocs
