source:
  kind: ConfigMap
  version: v1
  name: default-etos-service-versions
  fieldPath: data.eventRepositoryStorage
targets:
  - select:
      kind: CustomResourceDefinition
      group: apiextensions.k8s.io
      version: v1
      name: clusters.etos.eiffel-community.github.io
    fieldPaths:
      - .spec.versions.0.schema.openAPIV3Schema.properties.spec.properties.eventRepository.properties.storage.properties.image.default
    options:
      create: true
