apiVersion: etos.eiffel-community.github.io/v1alpha1
kind: Provider
metadata:
  labels:
    app.kubernetes.io/name: etos
    app.kubernetes.io/managed-by: kustomize
  name: iut-provider-sample
spec:
  type: iut
  host: http://etos-iut.etos-test.svc.cluster.local/iut
  image: example.com/iut-provider:v0.0.1
