apiVersion: etos.eiffel-community.github.io/v1alpha2
kind: LogArea
metadata:
  labels:
    app.kubernetes.io/name: etos
    app.kubernetes.io/managed-by: kustomize
  name: logarea-sample
spec:
  provider_id: log-area-provider-sample
