# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/etos.eiffel-community.github.io_testruns.yaml
- bases/etos.eiffel-community.github.io_providers.yaml
- bases/etos.eiffel-community.github.io_environments.yaml
- bases/etos.eiffel-community.github.io_clusters.yaml
- bases/etos.eiffel-community.github.io_environmentrequests.yaml
# +kubebuilder:scaffold:crdkustomizeresource
- default_images_configmap.yaml

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- path: patches/webhook_in_providers.yaml
- path: patches/webhook_in_testruns.yaml
- path: patches/webhook_in_environmentrequests.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch
- path: defaults/api.yaml
  target:
    kind: CustomResourceDefinition
    group: apiextensions.k8s.io
    version: v1
    name: clusters.etos.eiffel-community.github.io

replacements:
- path: defaults/sse.yaml
- path: defaults/logarea.yaml
- path: defaults/environment_provider.yaml
- path: defaults/suite_runner.yaml
- path: defaults/log_listener.yaml
- path: defaults/suite_starter.yaml
- path: defaults/test_runner.yaml
- path: defaults/event_repository_api.yaml
- path: defaults/event_repository_storage.yaml

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
